### ISSUE TITLE
Error after setting up connection with Reddit...

### ISSUE THREAD

**Issue by suprix** [corbindavenport/tootbot#13]
[ OK ] You have the latest version of Tootbot (2.0)
[ OK ] Sucessfully authenticated on Twitter as @my username
[ OK ] Setting up connection with Reddit...
Traceback (most recent call last):
  File "tootbot.py", line 358, in <module>
    subreddit = setup_connection_reddit(SUBREDDIT_TO_MONITOR)
  File "tootbot.py", line 54, in setup_connection_reddit
    return r.subreddit(subreddit)
  File "C:\Users\**\AppData\Local\Programs\Python\Python36\lib\site-packages
\praw\models\helpers.py", line 164, in __call__
    return Subreddit(self._reddit, display_name=display_name)
  File "C:\Users\**\AppData\Local\Programs\Python\Python36\lib\site-packages
\praw\models\reddit\subreddit.py", line 319, in __init__
    'Either `display_name` or `_data` must be provided.')
TypeError: Either `display_name` or `_data` must be provided.

C:\Users\**\Desktop\mini projects-js\projects\tootbot-master>

**Comment by corbindavenport** [comment]
Can you post your config.ini file?

**Comment by suprix** [comment]
# This is the config file for Tootbot! You must restart the bot for any changes to take effect.

# General settings
[BotSettings]
# File name for the cache spreadsheet (default is 'cache.csv')
CacheFile: cache.csv
# Minimum delay between social media posts, in seconds (default is '600')
DelayBetweenPosts: 600
# Minimum position of post on subreddit front page that the bot will look at (default is '10')
PostLimit: 10
# Name of subreddit to take posts from (example: 'gaming')
# Multiple subreddits can be used like this: 'gaming+funny+news'
SubredditToMonitor: 
# Allow NSFW Reddit posts to be posted by the bot
# NSFW posts will be hidden behind a content warning on Mastodon, regardless of this setting
NSFWPostsAllowed: false
# Allow Reddit self-posts to be posted by the bot
SelfPostsAllowed: true

# Settings related to media attachments
[MediaSettings]
# Folder name for media downloads (default is 'media')
MediaFolder: media
# Set the bot to only post Reddit posts that directly link to media
# Links from Gfycat, Giphy, Imgur, i.redd.it, and i.reddituploads.com are currently supported
MediaPostsOnly: false

# Twitter settings
[Twitter]
# Enable or disable Twitter posting
PostToTwitter: true

# Mastodon settings
[Mastodon]
# Name of instance to log into (example: mastodon.social), leave blank to disable Mastodon posting
InstanceDomain: 


I haven't changed anything in here.

**Comment by suprix** [comment]
https://hastebin.com/esinoyices.pas
there you go. I haven't changed anything.

**Comment by suprix** [comment]
hey, sorry forgot to add reddit topic...
