### ISSUE TITLE
Tweet title

### ISSUE THREAD

**Issue by suprix** [corbindavenport/tootbot#14]
hey, how can i make so my tweets from bot doesn't have title that's on reddit?
Like "ImYourMeme - https://redd.it/...."
Thanks in advance!

**Comment by corbindavenport** [comment]
There isn't a setting for it. The easiest way to change it is by adding this after line 29 of tootbot.py:

```
submission.title = "ImYourMeme"
```

**Comment by suprix** [comment]
thx

**Comment by suprix** [comment]
@corbindavenport I'm getting this error when I try to run it again.
`
  File "tootbot.py", line 30
    submission.title = "ImYourMeme"
             ^
IndentationError: expected an indented block
`
