### ISSUE TITLE
Add support for Heroku

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/tootbot#19]
https://devcenter.heroku.com/articles/how-heroku-works

https://devcenter.heroku.com/articles/heroku-button

**Comment by corbindavenport** [comment]
https://heroku.com/deploy?template=https://github.com/corbindavenport/tootbot/tree/dev

**Comment by DM2602** [comment]
Site says
"No app.json located in the repo URL provided.
Make sure that an app.json file exists in the project root directory."

**Comment by corbindavenport** [comment]
Because the dev branch was merged into master. Heroku doesn't work yet anyways, I have to make a separate version of the script that stores settings in Heroku's evironment variables instead of config.ini.

**Comment by corbindavenport** [comment]
Progress!
![capture](https://user-images.githubusercontent.com/3879063/41825470-957b7632-77ee-11e8-97d5-74270a5a1424.PNG)

**Comment by corbindavenport** [comment]
Progress!

![capture](https://user-images.githubusercontent.com/3879063/41825478-abf867b2-77ee-11e8-821d-c07c07ac0bd5.PNG)

**Comment by corbindavenport** [comment]
Current broken functionality:

- Setting 'false' as the variable for hashtags just makes every post have "#false" in it
- No Mastodon posting yet
- Cache file doesn't seem to save at all
