### ISSUE TITLE
multiple subreddits don't work as expected 

### ISSUE THREAD

**Issue by skatcat743** [corbindavenport/tootbot#21]
It likes picking the only the middle sub so if I have 'egg+box+can' it only picks from subreddit box and not from egg or can

**Comment by corbindavenport** [comment]
I just tried gaming+funny+news, and the first post came from /r/gaming and the second from /r/news. I'm guessing the other two subreddits you selected are far less popular than the middle one, or Reddit is doing something weird with its sorting algorithm.

Either way, there's nothing for me to fix here.
