### ISSUE TITLE
Error while posting tweet: 'charmap' codec can't encode character '\U0001f64f' in position 2: character maps to <undefined>

### ISSUE THREAD

**Issue by ACupOfSaltTV** [corbindavenport/tootbot#24]
im getting this error "Error while posting tweet: 'charmap' codec can't encode character '\U0001f64f' in position 2: character maps to <undefined>"

i have python 3.5.3, I'm running on windows server 2016 and my config file is here https://pastebin.com/qVLziexK

**Comment by ACupOfSaltTV** [comment]
after a lot of research i fixed it with this bat file

@echo off
setlocal
chcp 65001
set PYTHONIOENCODING=utf-8
python tootbot.py

**Comment by corbindavenport** [comment]
Hmm, I wonder if there is anything that can be added to Tootbot to avoid this.
