### ISSUE TITLE
KeyError: 'BotSettings'

### ISSUE THREAD

**Issue by Arlodotexe** [corbindavenport/tootbot#27]
I'm getting the following error when running `tootbot.py`:

```
[ OK ] You have the latest version of Tootbot (2.2)
Traceback (most recent call last):
  File ".\tootbot-2.2\tootbot.py", line 203, in <module>
    CACHE_CSV = config['BotSettings']['CacheFile']
  File "C:\Users\chuck\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'BotSettings'
```

It worked not long ago and I haven't changed anything major, what do I do about this?

**Comment by corbindavenport** [comment]
What does your config.ini file look like?

**Comment by isthistechsupport** [comment]
Just had the same error, happens when your current folder isn't the tootbot files folder. If you're trying to run it like this

    user~> python3 ~/tootbot/tootbot.py

I'd recommend trying 

    user~> cd /home/user/tootbot
    user~/tootbot> python3 tootbot.py

instead.

**Comment by corbindavenport** [comment]
Ah yeah, the wiki says to set your directory to the Tootbot folder before running.
