### ISSUE TITLE
Add support for higher-quality video uploads to Mastodon

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/tootbot#3]
The Tweepy library requires Twitter media uploads to be an image/GIF and under 3MB. Mastodon.py allows full video uploads up to 8MB. Tootbot should be updated to use higher-quality media uploads when posting to Mastodon.

**Comment by joachimesque** [comment]
Yes. I would love for the original imgur/gfycat video to be used (or converted to a smaller vid if the file is too heavy), instead of a gif conversion

**Comment by Stevio2000** [comment]
Heya, is anyone still working on this or an option to ignore gifs. I'd rather not post gifs than some low quality gif.

**Comment by corbindavenport** [comment]
This is still something I'd like to get working, I just haven't had the time. I was hoping to wait until the Twitter API (Tweepy) added support for MP4 uploads, so I could use the same code for both social networks, but it doesn't look like that will happen anytime soon.

I'll try to get this working this weekend.

**Comment by corbindavenport** [comment]
This is now working on the `mastodon-video` branch! When posting to Mastodon, MP4 versions of media (if available) from Imgur, Gfycat, and Giphy will be used. Once I add a few minor tweaks and test everything, I'll release a new Tootbot version (2.4) with this feature.

![capture](https://user-images.githubusercontent.com/3879063/45913398-b1142e00-bdff-11e8-9137-400031cdc78c.PNG)

**Comment by corbindavenport** [comment]
This feature is part of the latest Tootbot update!
