### ISSUE TITLE
Error when running the script 

### ISSUE THREAD

**Issue by disvekt** [corbindavenport/tootbot#33]
when i run the script using "python tootbot.py" 
i get this message - 
"Error in main process: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04898030>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))"
ples help thx

**Comment by corbindavenport** [comment]
That sounds like a system configuration issue. Maybe you have a firewall or some other proxy turned on?

**Comment by disvekt** [comment]
I still get the same error. I dont know if this helps or not but i use a
vpn because reddit is blocked in my country.
Thx

On Thu, Jun 21, 2018 at 11:28 PM, Corbin Davenport <notifications@github.com

**Comment by corbindavenport** [comment]
Maybe Python isn't communicating through the VPN or something? This isn't anything I can fix, so I'm closing.
