### ISSUE TITLE
Can't run with systemctl

### ISSUE THREAD

**Issue by isthistechsupport** [corbindavenport/tootbot#35]
Hi, I'm trying to set tootbot to run with systemctl on a VM. When I SSH in I can run

    ~/tootbot> /usr/bin/python3 ~/tootbot/tootbot.py

And it'll run properly. But with my `tootbot.service` file like this

    WorkingDirectory=/home/isthistechsupport/tootbot/
    ExecStart=/usr/bin/python3 /home/isthistechsupport/tootbot/tootbot.py

It simply throws this error

    Jun 21 20:20:21 vm python3[76763]:   File "/home/isthistechsupport/tootbot/tootbot.py", line 1, in <module>
    Jun 21 20:20:21 vm python3[76763]:     import praw
    Jun 21 20:20:21 vm python3[76763]: ImportError: No module named 'praw'

What am I missing here? I don't want to make the bot execution depend upon a SSH session for obvious reasons, and I can't remote into this VM either.

**Comment by corbindavenport** [comment]
Hmm, that's very odd. Is the systemctl running as the same user account you set up Tootbot with? Maybe the service is running as root instead.

If you can't figure it out, maybe try placing the pip command in the service (at least initially):

```
pip3 install -r requirements.txt
```

Obviously make sure you're in the install directory for that command too.

**Comment by isthistechsupport** [comment]
Ah, yes, that made it work! Thanks for the help
