### ISSUE TITLE
Error and i dont know how anything works

### ISSUE THREAD

**Issue by JohnArmstrong117** [corbindavenport/tootbot#36]
[EROR] Error in main process: HTTP Error 429: Too Many Requests
[ OK ] Sleeping for 500 seconds
Traceback (most recent call last):
  File "tootbot.py", line 435, in <module>
    time.sleep(DELAY_BETWEEN_TWEETS)

I'm really new and just need an explanation of what i need to do

**Comment by corbindavenport** [comment]
What are the contents of your `config.ini` file?

**Comment by JohnArmstrong117** [comment]
# This is the config file for Tootbot! You must restart the bot for any changes to take effect.

# General settings
[BotSettings]
# File name for the cache spreadsheet (default is 'cache.csv')
CacheFile: cache.csv
# Minimum delay between social media posts, in seconds (default is '600')
DelayBetweenPosts: 600
# Minimum position of post on subreddit front page that the bot will look at (default is '10')
PostLimit: 10
# Name of subreddit to take posts from (example: 'gaming')
# Multiple subreddits can be used like this: 'gaming+funny+news'
SubredditToMonitor: me_irl
# Allow NSFW Reddit posts to be posted by the bot
# NSFW media will be marked as sensitive, regardless of this setting
NSFWPostsAllowed: false
# Allow Reddit posts marked as spoilers to be posted by the bot
SpoilersAllowed: true
# Allow Reddit self-posts to be posted by the bot
SelfPostsAllowed: true
# List of hashtags to be used on every post, separated by commas without # symbols (example: hashtag1, hashtag2)
# Leaving this blank will disable hashtags
Hashtags: 

# Settings related to media attachments
[MediaSettings]
# Folder name for media downloads (default is 'media')
MediaFolder: media
# Set the bot to only post Reddit posts that directly link to media
# Links from Gfycat, Giphy, Imgur, i.redd.it, and i.reddituploads.com are currently supported
MediaPostsOnly: true

# Twitter settings
[Twitter]
# Enable or disable Twitter posting
PostToTwitter: true

# Mastodon settings
[Mastodon]
# Name of instance to log into (example: mastodon.social), leave blank to disable Mastodon posting
InstanceDomain: 
# Sets all media attachments as sensitive media, this should be left on 'true' in most cases (note: images from NSFW Reddit posts will always be marked as sensitive)
# More info: https://gist.github.com/joyeusenoelle/74f6e6c0f349651349a0df9ae4582969#what-does-cw-mean
SensitiveMedia: true

**Comment by imatrixgp** [comment]
It also happens to me somethings idk why

**Comment by corbindavenport** [comment]
Closed due to inactivity.
