### ISSUE TITLE
Getting error about 'SubredditToMonitor'

### ISSUE THREAD

**Issue by zeldro** [corbindavenport/tootbot#37]
So, I edit config.ini, put all of my desired settings in, yadda yadda yadda. I put in my desired subreddit like so: 

`SubredditToMonitor: (sub here)#`

And when I save and open cmd & type `python tootbot.py` however, I get an error revolving around SUBREDDIT_TO_MONITOR and a thing that says "KeyError: SubredditToMonitor"

Idk what to do, can someone help? Thanks

**Comment by corbindavenport** [comment]
It should be formatted like `SubredditToMonitor: funny`. No hashtag afterwards.

**Comment by zeldro** [comment]
now it's giving me an error about allowing nsfw posts for the bot...

here's all of the config file

`# This is the config file for Tootbot! You must restart the bot for any changes to take effect.

# General settings
[BotSettings]
# File name for the cache spreadsheet (default is 'cache.csv')
CacheFile: cache.csv
# Minimum delay between social media posts, in seconds (default is '600')
DelayBetweenPosts: 3600
# Minimum position of post on subreddit front page that the bot will look at (default is '10')
PostLimit: 10
# Name of subreddit to take posts from (example: 'gaming')
# Multiple subreddits can be used like this: 'gaming+funny+news'SubredditToMonitor: anime_irl
 Allow NSFW Reddit posts to be posted by the bot
# NSFW media will be marked as sensitive, regardless of this setting
NSFWPostsAllowed: false
# Allow Reddit posts marked as spoilers to be posted by the bot
SpoilersAllowed: true
# Allow Reddit self-posts to be posted by the bot
SelfPostsAllowed: false
# List of hashtags to be used on every post, separated by commas without # symbols (example: hashtag1, hashtag2)
# Leaving this blank will disable hashtags
Hashtags: 

# Settings related to media attachments
[MediaSettings]
# Folder name for media downloads (default is 'media')
MediaFolder: media
# Set the bot to only post Reddit posts that directly link to media
# Links from Gfycat, Giphy, Imgur, i.redd.it, and i.reddituploads.com are currently supported
MediaPostsOnly: true

# Twitter settings
[Twitter]
# Enable or disable Twitter posting
PostToTwitter: true

# Mastodon settings
[Mastodon]
# Name of instance to log into (example: mastodon.social), leave blank to disable Mastodon posting
InstanceDomain: 
# Sets all media attachments as sensitive media, this should be left on 'true' in most cases (note: images from NSFW Reddit posts will always be marked as sensitive)
# More info: https://gist.github.com/joyeusenoelle/74f6e6c0f349651349a0df9ae4582969#what-does-cw-mean
SensitiveMedia: true`

**Comment by corbindavenport** [comment]
You removed the comment (#) from the beginning of this line:
`Allow NSFW Reddit posts to be posted by the bot`

And there's no value at all for `SubredditToMonitor`.

**Comment by corbindavenport** [comment]
Closed due to inactivity.
