### ISSUE TITLE
"Error in main process"

### ISSUE THREAD

**Issue by vincenthamma** [corbindavenport/tootbot#42]
Hey,
When I try running the bot it sucessfully authenticates with my twitter, but when it tries setting up connection with Reddit it says:
"[EROR] Error in main process: Either `display_name` or `_data` must be provided."
I've only changed the line in the config file that specifies the subreddit (SubredditToMonitor: *subreddit*)
What should I do?

**Comment by corbindavenport** [comment]
What's your full `config.ini` file?

**Comment by corbindavenport** [comment]
Try moving your bot to Heroku and see if it makes any difference: https://github.com/corbindavenport/tootbot/wiki/Moving-from-local-install-to-Heroku

Re-open this issue if you have any more problems.
