### ISSUE TITLE
keep getting error "too many requests"

### ISSUE THREAD

**Issue by zeldro** [corbindavenport/tootbot#45]
Every time I boot up the bot I'm greeted with it ignoring a few posts because they're already posted and then saying "[EROR] Error in main process: HTTP Error 429: Too Many  Requests" and then it starts sleeping. Repeats when it wakes back up too, I don't know what to do.

**Comment by corbindavenport** [comment]
You might have been rate-limited by Reddit. Keep the bot off for a few hours, and try again.
