### ISSUE TITLE
KeyError: 'BotSettings'

### ISSUE THREAD

**Issue by ImTeme** [corbindavenport/tootbot#46]
So I'm getting a KeyError after I wrote python tootbot.py and all my Paths are set correctly. It says 'Python\Python36-32\lib\configparser.py', line 959 in __getitem__ raise KeyError(key)
KeyError: 'BotSettings'

**Comment by ImTeme** [comment]
I only changed the Subreddit 

![notepad _2018-06-25_15-36-09](https://user-images.githubusercontent.com/38312492/41853176-73843952-788d-11e8-9471-02d383b33d50.png)

**Comment by corbindavenport** [comment]
I think I see the problem, there isn't supposed to be apostrophes in the `SubredditToMonitor` setting. So you need to change that line to this:

```
SubredditToMonitor: blep
```

**Comment by ImTeme** [comment]
The thing is, it still gets the same Error even without the apostrophes :/

**Comment by corbindavenport** [comment]
Are you still having this problem on the latest version of Tootbot?

**Comment by ImTeme** [comment]
Nope. It's fixed. Thank you very much!!
