### ISSUE TITLE
[EROR] Error in main process: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Jessomadic** [corbindavenport/tootbot#47]
I made a bot that reads off of the PCMR subreddit and posts it to twitter. It worked well so I left it going overnight. I went back downstairs this morning to find this. 
![image](https://user-images.githubusercontent.com/35648348/41861250-b96ee58a-786e-11e8-87cf-12e772a29839.png) Is there a way to fix this or did reddit ban my bot

**Comment by corbindavenport** [comment]
Has the Reddit account associated with the bot been banned from PCMR? Try leaving a comment or something.

Another thing you can try is creating a new set of Reddit API keys.

**Comment by Jessomadic** [comment]
I ended up setting up new API keys and it is currently working. I will post here again if it happens again

**Comment by corbindavenport** [comment]
Hmm, maybe Reddit flagged those keys or something. Oh well.
