### ISSUE TITLE
How to run Tootbot at startup!

### ISSUE THREAD

**Issue by imatrixgp** [corbindavenport/tootbot#48]
**I hope you add this to the instructions 👍** 
First, I used a bat file that you posted on Twitter:
@echo off
cd "C:\Users\... Location of Tootbot..."
:python
py ./tootbot.py
goto python

Save it to "run.bat". Then you have to create a shortcut to desktop of that batch file. Finally you press WINDOWS BUTTON + R, and write "shell:startup". Restart your PC and its done

**Comment by corbindavenport** [comment]
I'm in the process of re-working the wiki, I'll make sure this gets added in.

**Comment by corbindavenport** [comment]
Added instructions to the wiki.
