### ISSUE TITLE
HTTP Error 429 from Imgur API

### ISSUE THREAD

**Issue by imatrixgp** [corbindavenport/tootbot#51]
Is there a way so when getting posts from Reddit it removes the one that have a Imgur image link? Is causing me a lot of problems with their rate limiting and in Heroku it automatically crashes when that happens..

**Comment by imatrixgp** [comment]
Also, i think this only happens in Heroku

**Comment by corbindavenport** [comment]
I still don't know why this is happening. My only guess is that because Heroku shares resources on free dynos, maybe the same IP is being used for multiple Tootbot instances, thus causing Imgur to think the same device is hitting it multiple times.

Again, that's just a guess. Have you tried making a new set of Imgur API keys?

**Comment by imatrixgp** [comment]
Yes but it says that same

**Comment by Jessomadic** [comment]
I am also getting this without using Heroku. making new API keys does not work

**Comment by freaky767** [comment]
I actually got a HTTP Error 429 as well, not running on Heroku though, just my local pc.

**Comment by corbindavenport** [comment]
I just sent the below message to Imgur Support:

> Hello,
> 
> I'm the developer of Tootbot, a Python application that mirrors Reddit links to Twitter: https://github.com/corbindavenport/tootbot
> 
> One of the features of Tootbot is that it media from Gfycat/Imgur/Giphy is directly attached in the social media post. For example, if an Imgur image is linked on Reddit, Tootbot will download the image and attach it when posting a tweet.
> 
> I'm using the official Imgur Python library for authentication and grabbing the direct URLs for gallery/album links. However, many users are seeing an 'Error 429' from the Imgur API while Tootbot tries to authenticate. Several reports can be found here: https://github.com/corbindavenport/tootbot/issues/51
> 
> I see from the API documentation that Error 429 means the account is being rate-limited, but I don't see why that should be happening. Tootbot requires the admin to add their own API keys, and most bots are only checking for new Reddit posts (and thus, possibly pinging the Imgur API) once every 10-15 minutes. I personally operate two Tootbot instances, both of which only check for new posts every 30 minutes, and I'm seeing this error as well.
> 
> Is there something wrong with the Imgur API? Is it normal for an application to be rate-limited if it's making only one request every 10-30 minutes? Any help would be appreciated.
> 
> Corbin

**Comment by freaky767** [comment]
Now I'm getting HTTP Error 403: Forbidden error

**Comment by freaky767** [comment]
![image](https://user-images.githubusercontent.com/23425837/43212306-8577de74-902b-11e8-88b3-b296dbf9f2e5.png)

**Comment by freaky767** [comment]
I think they fixed it, as I have not gotten any errors for the past 2+ days.

**Comment by Jessomadic** [comment]
@corbindavenport same. I think everything is good now!

**Comment by corbindavenport** [comment]
Weird, I never even got a response from Imgur. I'll close this issue then.
