### ISSUE TITLE
Heroku script reposting content repeatedly

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/tootbot#52]
It turns out Heroku wipes all local storage approximately once a day, instead of on every reboot like I originally thought: https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

This causes the cache file to be wiped at least once a day, causing frequent reposts. As such, I'm recommending people do not set up new Heroku bots right now. I'm hoping to fix this soon (by caching posts in environment variables instead), and updates will be posted in this thread.

**Comment by Syfaro** [comment]
It's probably worth looking into something like [Postgres](https://elements.heroku.com/addons/heroku-postgresql), which is free for less than 10,000 rows on Heroku. Using something like SQLAlchemy means you could support SQLite for local and Postgres for production without additional code for either. 

Alternatively, [Redis](https://elements.heroku.com/addons/heroku-redis) (also free on Heroku for less than 25MB of RAM) could work too which might require less code.

**Comment by corbindavenport** [comment]
I was hoping to store the last ~15 posts in a Heroku variable, but it looks like Heroku doesn't allow scripts to set variables at all, only the user. I'll look into Postgres and Redis, thanks @Syfaro!

**Comment by corbindavenport** [comment]
Fixed in Tootbot 2.3.
