### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by AniShalev** [corbindavenport/tootbot#53]
"[EROR] Error in main process: 'ascii' codec can't encode characters in position 41-44: ordinal not in range(128)"
![image](https://user-images.githubusercontent.com/37079378/41995330-fbf39490-7a59-11e8-8dcb-fa830f9e5066.png)

**Comment by corbindavenport** [comment]
Does this still happen on the latest version of Tootbot?

**Comment by AniShalev** [comment]
i already fixed this. i forget to close.
