### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by freaky767** [corbindavenport/tootbot#59]
I get this Syntax Error while trying to start up Tootbot.
![6gw8w9a](https://user-images.githubusercontent.com/23425837/42139432-c42f08ee-7d85-11e8-8ed4-50acb4e3dcee.png)
I am very new, so don't hate on meh pls.

**Comment by freaky767** [comment]
And I also get an error for the requirements
https://i.imgur.com/BfRNodq.png

**Comment by corbindavenport** [comment]
Try running the requirements command again, I think Pip was having download issues.

**Comment by freaky767** [comment]
I tried again for the requirements, using pip3 and pip, but still get the same error.

**Comment by spotlightishere** [comment]
It seems this is an issue with Python 3.(6? 7? Don't follow it enough to figure out.)

Downgrading to Python 3.4 solved this error in the meantime.

**Comment by Syfaro** [comment]
[`async` is a reserved keyword in Python 3.7](https://docs.python.org/3/whatsnew/3.7.html)

**Comment by corbindavenport** [comment]
Huh, I had no idea about that. I'll make a note on the wiki about installing Python 3.6.x. [The Heroku version uses Python 3.3.6](https://github.com/corbindavenport/tootbot/blob/master/runtime.txt), so there's no issue there.

**Comment by freaky767** [comment]
Okay, ill try to downgrade my Python.

**Comment by freaky767** [comment]
that actually fixed it! thank you!
