### ISSUE TITLE
Changed bot entirely, @me_irlreddit to @dogpostingbot + changed subreddits

### ISSUE THREAD

**Issue by melleomars** [corbindavenport/tootbot#62]
hey so I figured a while ago it'd be the best to instead of maintaining another r/me_irl bot i could make another dog bot. so now the handle is @dogpostingbot. The subreddits it follows are now r/WiggleButts (aussie dog subreddit) r/corgis r/goldenretrievers r/labrador and r/Blacklabs. also please remove @me_irlreddit since it doesn't exist now.

**Comment by melleomars** [comment]
oops forgot r/sheltie

**Comment by corbindavenport** [comment]
Done!
