### ISSUE TITLE
Discord posting support

### ISSUE THREAD

**Issue by Jessomadic** [corbindavenport/tootbot#65]
How hard would it be so that instead of reposting to Twitter it could repost a Discord Bot?

**Comment by corbindavenport** [comment]
I don't have any experience with the Discord API. Looks like there's a Python library for it: https://github.com/Rapptz/discord.py

I'm not going to add this feature myself, but if someone wants to work on it, I'll accept any pull requests.

**Comment by Jessomadic** [comment]
Yeah, I saw that Lib and I was messing around with it but it does not seem to want to install somethings that it needs and it won't manually either so I am going to boot up the good old Linux VM tomorrow and see what I can do :)

**Comment by Jessomadic** [comment]
Guess it did not want to run as Python3 but Python -_-

**Comment by Jessomadic** [comment]
Making good progress :)
![image](https://user-images.githubusercontent.com/35648348/42862202-859e3bb4-8a2c-11e8-9223-53acd5d86b84.png)

**Comment by Jessomadic** [comment]
I have it working 100% of the time and have written a tut for it. I plan to fully integrate it in the future. but right now it's 3Am almost and I have work tomorrow :)
[Tootbot for discord as well.zip](https://github.com/corbindavenport/tootbot/files/2204679/Tootbot.for.discord.as.well.zip)

**Comment by Jessomadic** [comment]
So looking at it, It looks like if Webhook was implemented into TootBot it could be implemented pretty easily. As of now 7/19/2018 you must have two clients open to make the bot post from Reddit to twitter to Discord. One of these being Tootbot and then other being The Discord API bot that is in the folder above along with a tut to learn to set it up. It is in a Docx format so pics could be used to show what screen should look like when done. As of now, I can't go any further as I don't know how to implement Webhook

**Comment by corbindavenport** [comment]
I'm closing this for now. If someone wants to finish Discord support and update the code to the latest version of Tootbot, I can merge it.
