### ISSUE TITLE
What happens after the bot reaches its limit?

### ISSUE THREAD

**Issue by Mihuuuu** [corbindavenport/tootbot#90]
I've tried setting the bot limit to 2 and make it post every 10 seconds to see what it'll do and after those two posts and it'll just be stuck in a continuous loop of searching for posts. 
Does it just post every time something new gets onto the hot page? I'm kinda confused.

**Comment by corbindavenport** [comment]
The post limit is how many posts down on the front page of a subreddit the bot will check. So in your case, it will only check the top 2 posts, and it won't post something new until a post gets to the #2 spot. I recommend setting a larger limit and a longer refresh so you don't max out the Reddit API.
