### ISSUE TITLE
When I entered all my details I saw something weird

### ISSUE THREAD

**Issue by CSkya32** [corbindavenport/tootbot#91]

**Comment by CSkya32** [comment]
I entered my reddit secret imgur secret(...)after that it said something like logging in with @mytwitterusername, even if I created an app which is not called like my username on twitter

**Comment by corbindavenport** [comment]
That's the bot telling you what Twitter account its logged into, the app name has nothing to do with it.

**Comment by CSkya32** [comment]
Thanks for the reply, does that mean that the bot is using my twitter account to post things?

**Comment by corbindavenport** [comment]
It's using whatever Twitter account it says it logged into.
